=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module Checkify
  class Account < ApiModelBase
    attr_accessor :plan

    attr_accessor :plan_name

    attr_accessor :status

    # ISO 8601 date when subscription ends (only when status is cancelling)
    attr_accessor :cancels_at

    attr_accessor :units_used

    attr_accessor :units_limit

    attr_accessor :units_remaining

    attr_accessor :period_start

    attr_accessor :period_end

    # Per-endpoint call counts for the current period
    attr_accessor :usage

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'plan' => :'plan',
        :'plan_name' => :'plan_name',
        :'status' => :'status',
        :'cancels_at' => :'cancels_at',
        :'units_used' => :'units_used',
        :'units_limit' => :'units_limit',
        :'units_remaining' => :'units_remaining',
        :'period_start' => :'period_start',
        :'period_end' => :'period_end',
        :'usage' => :'usage'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'plan' => :'String',
        :'plan_name' => :'String',
        :'status' => :'String',
        :'cancels_at' => :'Date',
        :'units_used' => :'Integer',
        :'units_limit' => :'Integer',
        :'units_remaining' => :'Integer',
        :'period_start' => :'Date',
        :'period_end' => :'Date',
        :'usage' => :'Hash<String, Integer>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'cancels_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Checkify::Account` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Checkify::Account`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'plan')
        self.plan = attributes[:'plan']
      end

      if attributes.key?(:'plan_name')
        self.plan_name = attributes[:'plan_name']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'cancels_at')
        self.cancels_at = attributes[:'cancels_at']
      end

      if attributes.key?(:'units_used')
        self.units_used = attributes[:'units_used']
      end

      if attributes.key?(:'units_limit')
        self.units_limit = attributes[:'units_limit']
      end

      if attributes.key?(:'units_remaining')
        self.units_remaining = attributes[:'units_remaining']
      end

      if attributes.key?(:'period_start')
        self.period_start = attributes[:'period_start']
      end

      if attributes.key?(:'period_end')
        self.period_end = attributes[:'period_end']
      end

      if attributes.key?(:'usage')
        if (value = attributes[:'usage']).is_a?(Hash)
          self.usage = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      plan_validator = EnumAttributeValidator.new('String', ["free", "starter", "business", "enterprise"])
      return false unless plan_validator.valid?(@plan)
      status_validator = EnumAttributeValidator.new('String', ["free", "active", "cancelling", "cancelled", "past_due", "incomplete"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] plan Object to be assigned
    def plan=(plan)
      validator = EnumAttributeValidator.new('String', ["free", "starter", "business", "enterprise"])
      unless validator.valid?(plan)
        fail ArgumentError, "invalid value for \"plan\", must be one of #{validator.allowable_values}."
      end
      @plan = plan
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["free", "active", "cancelling", "cancelled", "past_due", "incomplete"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          plan == o.plan &&
          plan_name == o.plan_name &&
          status == o.status &&
          cancels_at == o.cancels_at &&
          units_used == o.units_used &&
          units_limit == o.units_limit &&
          units_remaining == o.units_remaining &&
          period_start == o.period_start &&
          period_end == o.period_end &&
          usage == o.usage
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [plan, plan_name, status, cancels_at, units_used, units_limit, units_remaining, period_start, period_end, usage].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
