=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module Checkify
  class AcnResponse < ApiModelBase
    attr_accessor :abn

    attr_accessor :abn_formatted

    attr_accessor :acn

    attr_accessor :acn_formatted

    attr_accessor :entity_name

    attr_accessor :entity_type

    attr_accessor :abn_details

    attr_accessor :acn_details

    attr_accessor :addresses

    attr_accessor :former_names

    attr_accessor :documents

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'abn' => :'abn',
        :'abn_formatted' => :'abnFormatted',
        :'acn' => :'acn',
        :'acn_formatted' => :'acnFormatted',
        :'entity_name' => :'entityName',
        :'entity_type' => :'entityType',
        :'abn_details' => :'abnDetails',
        :'acn_details' => :'acnDetails',
        :'addresses' => :'addresses',
        :'former_names' => :'formerNames',
        :'documents' => :'documents'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'abn' => :'String',
        :'abn_formatted' => :'String',
        :'acn' => :'String',
        :'acn_formatted' => :'String',
        :'entity_name' => :'String',
        :'entity_type' => :'String',
        :'abn_details' => :'AcnResponseAbnDetails',
        :'acn_details' => :'AcnResponseAcnDetails',
        :'addresses' => :'Array<AcnAddress>',
        :'former_names' => :'Array<FormerName>',
        :'documents' => :'Array<AsicDocument>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'abn',
        :'abn_formatted',
        :'abn_details',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Checkify::AcnResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Checkify::AcnResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'abn')
        self.abn = attributes[:'abn']
      end

      if attributes.key?(:'abn_formatted')
        self.abn_formatted = attributes[:'abn_formatted']
      end

      if attributes.key?(:'acn')
        self.acn = attributes[:'acn']
      end

      if attributes.key?(:'acn_formatted')
        self.acn_formatted = attributes[:'acn_formatted']
      end

      if attributes.key?(:'entity_name')
        self.entity_name = attributes[:'entity_name']
      end

      if attributes.key?(:'entity_type')
        self.entity_type = attributes[:'entity_type']
      end

      if attributes.key?(:'abn_details')
        self.abn_details = attributes[:'abn_details']
      end

      if attributes.key?(:'acn_details')
        self.acn_details = attributes[:'acn_details']
      end

      if attributes.key?(:'addresses')
        if (value = attributes[:'addresses']).is_a?(Array)
          self.addresses = value
        end
      end

      if attributes.key?(:'former_names')
        if (value = attributes[:'former_names']).is_a?(Array)
          self.former_names = value
        end
      end

      if attributes.key?(:'documents')
        if (value = attributes[:'documents']).is_a?(Array)
          self.documents = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          abn == o.abn &&
          abn_formatted == o.abn_formatted &&
          acn == o.acn &&
          acn_formatted == o.acn_formatted &&
          entity_name == o.entity_name &&
          entity_type == o.entity_type &&
          abn_details == o.abn_details &&
          acn_details == o.acn_details &&
          addresses == o.addresses &&
          former_names == o.former_names &&
          documents == o.documents
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [abn, abn_formatted, acn, acn_formatted, entity_name, entity_type, abn_details, acn_details, addresses, former_names, documents].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
