=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module Checkify
  class AddressDetails < ApiModelBase
    # Flat/unit number and type
    attr_accessor :unit

    # Floor/level descriptor
    attr_accessor :level

    # Combined unit and level
    attr_accessor :unit_level

    # House/lot number
    attr_accessor :street_number

    # Street name only
    attr_accessor :street_name

    # Street type code (ST, RD, AVE…)
    attr_accessor :street_type

    # Number + full street name combined
    attr_accessor :street

    # Locality/suburb name
    attr_accessor :city

    # 4-digit postcode
    attr_accessor :postcode

    # State abbreviation (NSW, VIC…) — AU only
    attr_accessor :state

    # Full state name — AU only
    attr_accessor :state_full

    # Region/city (e.g. Auckland) — NZ only
    attr_accessor :region

    # Country code (AU or NZ)
    attr_accessor :country

    # Full country name
    attr_accessor :country_full

    attr_accessor :latitude

    attr_accessor :longitude

    # ABS Mesh Block identifier — AU only
    attr_accessor :mesh_block_code

    # Named building or complex — AU only
    attr_accessor :building_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'unit' => :'unit',
        :'level' => :'level',
        :'unit_level' => :'unitLevel',
        :'street_number' => :'streetNumber',
        :'street_name' => :'streetName',
        :'street_type' => :'streetType',
        :'street' => :'street',
        :'city' => :'city',
        :'postcode' => :'postcode',
        :'state' => :'state',
        :'state_full' => :'stateFull',
        :'region' => :'region',
        :'country' => :'country',
        :'country_full' => :'countryFull',
        :'latitude' => :'latitude',
        :'longitude' => :'longitude',
        :'mesh_block_code' => :'meshBlockCode',
        :'building_name' => :'buildingName'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'unit' => :'String',
        :'level' => :'String',
        :'unit_level' => :'String',
        :'street_number' => :'String',
        :'street_name' => :'String',
        :'street_type' => :'String',
        :'street' => :'String',
        :'city' => :'String',
        :'postcode' => :'String',
        :'state' => :'String',
        :'state_full' => :'String',
        :'region' => :'String',
        :'country' => :'String',
        :'country_full' => :'String',
        :'latitude' => :'Float',
        :'longitude' => :'Float',
        :'mesh_block_code' => :'String',
        :'building_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'unit',
        :'level',
        :'unit_level',
        :'state',
        :'state_full',
        :'region',
        :'latitude',
        :'longitude',
        :'mesh_block_code',
        :'building_name'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Checkify::AddressDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Checkify::AddressDetails`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'unit')
        self.unit = attributes[:'unit']
      end

      if attributes.key?(:'level')
        self.level = attributes[:'level']
      end

      if attributes.key?(:'unit_level')
        self.unit_level = attributes[:'unit_level']
      end

      if attributes.key?(:'street_number')
        self.street_number = attributes[:'street_number']
      end

      if attributes.key?(:'street_name')
        self.street_name = attributes[:'street_name']
      end

      if attributes.key?(:'street_type')
        self.street_type = attributes[:'street_type']
      end

      if attributes.key?(:'street')
        self.street = attributes[:'street']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'postcode')
        self.postcode = attributes[:'postcode']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'state_full')
        self.state_full = attributes[:'state_full']
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'country_full')
        self.country_full = attributes[:'country_full']
      end

      if attributes.key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.key?(:'mesh_block_code')
        self.mesh_block_code = attributes[:'mesh_block_code']
      end

      if attributes.key?(:'building_name')
        self.building_name = attributes[:'building_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          unit == o.unit &&
          level == o.level &&
          unit_level == o.unit_level &&
          street_number == o.street_number &&
          street_name == o.street_name &&
          street_type == o.street_type &&
          street == o.street &&
          city == o.city &&
          postcode == o.postcode &&
          state == o.state &&
          state_full == o.state_full &&
          region == o.region &&
          country == o.country &&
          country_full == o.country_full &&
          latitude == o.latitude &&
          longitude == o.longitude &&
          mesh_block_code == o.mesh_block_code &&
          building_name == o.building_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [unit, level, unit_level, street_number, street_name, street_type, street, city, postcode, state, state_full, region, country, country_full, latitude, longitude, mesh_block_code, building_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
