=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module Checkify
  class EmailResponse < ApiModelBase
    # Normalised (lowercased) email address
    attr_accessor :email

    # true only if both format and DNS checks pass
    attr_accessor :valid

    attr_accessor :format

    attr_accessor :dns

    attr_accessor :deliverable

    attr_accessor :can_connect_smtp

    attr_accessor :inbox_full

    attr_accessor :disabled

    attr_accessor :catch_all

    # Quality score — higher is better
    attr_accessor :score

    # Whether the email uses a free provider
    attr_accessor :free

    # Whether the email uses a disposable/temporary provider
    attr_accessor :disposable

    # Whether this is a role-based address (e.g. support@, info@)
    attr_accessor :role

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'email' => :'email',
        :'valid' => :'valid',
        :'format' => :'format',
        :'dns' => :'dns',
        :'deliverable' => :'deliverable',
        :'can_connect_smtp' => :'canConnectSmtp',
        :'inbox_full' => :'inboxFull',
        :'disabled' => :'disabled',
        :'catch_all' => :'catchAll',
        :'score' => :'score',
        :'free' => :'free',
        :'disposable' => :'disposable',
        :'role' => :'role'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'email' => :'String',
        :'valid' => :'Boolean',
        :'format' => :'EmailResponseFormat',
        :'dns' => :'EmailResponseDns',
        :'deliverable' => :'Boolean',
        :'can_connect_smtp' => :'Boolean',
        :'inbox_full' => :'Boolean',
        :'disabled' => :'Boolean',
        :'catch_all' => :'Boolean',
        :'score' => :'Float',
        :'free' => :'Boolean',
        :'disposable' => :'Boolean',
        :'role' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'deliverable',
        :'can_connect_smtp',
        :'inbox_full',
        :'disabled',
        :'catch_all',
        :'score',
        :'free',
        :'disposable',
        :'role'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Checkify::EmailResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Checkify::EmailResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'valid')
        self.valid = attributes[:'valid']
      end

      if attributes.key?(:'format')
        self.format = attributes[:'format']
      end

      if attributes.key?(:'dns')
        self.dns = attributes[:'dns']
      end

      if attributes.key?(:'deliverable')
        self.deliverable = attributes[:'deliverable']
      end

      if attributes.key?(:'can_connect_smtp')
        self.can_connect_smtp = attributes[:'can_connect_smtp']
      end

      if attributes.key?(:'inbox_full')
        self.inbox_full = attributes[:'inbox_full']
      end

      if attributes.key?(:'disabled')
        self.disabled = attributes[:'disabled']
      end

      if attributes.key?(:'catch_all')
        self.catch_all = attributes[:'catch_all']
      end

      if attributes.key?(:'score')
        self.score = attributes[:'score']
      end

      if attributes.key?(:'free')
        self.free = attributes[:'free']
      end

      if attributes.key?(:'disposable')
        self.disposable = attributes[:'disposable']
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@score.nil? && @score > 1
        invalid_properties.push('invalid value for "score", must be smaller than or equal to 1.')
      end

      if !@score.nil? && @score < 0
        invalid_properties.push('invalid value for "score", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@score.nil? && @score > 1
      return false if !@score.nil? && @score < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] score Value to be assigned
    def score=(score)
      if !score.nil? && score > 1
        fail ArgumentError, 'invalid value for "score", must be smaller than or equal to 1.'
      end

      if !score.nil? && score < 0
        fail ArgumentError, 'invalid value for "score", must be greater than or equal to 0.'
      end

      @score = score
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          email == o.email &&
          valid == o.valid &&
          format == o.format &&
          dns == o.dns &&
          deliverable == o.deliverable &&
          can_connect_smtp == o.can_connect_smtp &&
          inbox_full == o.inbox_full &&
          disabled == o.disabled &&
          catch_all == o.catch_all &&
          score == o.score &&
          free == o.free &&
          disposable == o.disposable &&
          role == o.role
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [email, valid, format, dns, deliverable, can_connect_smtp, inbox_full, disabled, catch_all, score, free, disposable, role].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
