=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'checkify/api_client'
require 'checkify/api_error'
require 'checkify/api_model_base'
require 'checkify/version'
require 'checkify/configuration'
require 'checkify/client'

# Models
require 'checkify/models/abn_address'
require 'checkify/models/abn_response'
require 'checkify/models/abn_response_abn_details'
require 'checkify/models/account'
require 'checkify/models/acn_address'
require 'checkify/models/acn_response'
require 'checkify/models/acn_response_abn_details'
require 'checkify/models/acn_response_acn_details'
require 'checkify/models/address_details'
require 'checkify/models/asic_document'
require 'checkify/models/asic_document_contents_inner'
require 'checkify/models/bulk_create_request'
require 'checkify/models/bulk_create_request_items'
require 'checkify/models/bulk_job'
require 'checkify/models/business_activity'
require 'checkify/models/business_activity_response'
require 'checkify/models/director_id_response'
require 'checkify/models/email_response'
require 'checkify/models/email_response_dns'
require 'checkify/models/email_response_format'
require 'checkify/models/error'
require 'checkify/models/former_name'
require 'checkify/models/name_availability'
require 'checkify/models/phone_response'
require 'checkify/models/postcode_result'
require 'checkify/models/reverse_result'
require 'checkify/models/sanctions_response'
require 'checkify/models/sanctions_result'
require 'checkify/models/sanctions_result_sanctions'
require 'checkify/models/suburb_details'
require 'checkify/models/tfn_response'

# APIs
require 'checkify/api/account_api'
require 'checkify/api/address_api'
require 'checkify/api/batch_api'
require 'checkify/api/business_api'
require 'checkify/api/communication_api'
require 'checkify/api/identity_api'

module Checkify
  class << self
    # Customize default settings for the SDK using block.
    #   Checkify.configure do |config|
    #     config.access_token = ENV.fetch("CHECKIFY_API_KEY")
    #     config.timeout = 30
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
