=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module Checkify
  class AddressApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Address autocomplete
    # Type-ahead address search across 17.8 M+ Australian and New Zealand addresses. Returns a map of address IDs to highlighted HTML strings. Costs 0 units. 
    # @param query [String] Search term, min 3 characters
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Hash<String, String>]
    def autocomplete(query, opts = {})
      data, _status_code, _headers = autocomplete_with_http_info(query, opts)
      data
    end

    # Address autocomplete
    # Type-ahead address search across 17.8 M+ Australian and New Zealand addresses. Returns a map of address IDs to highlighted HTML strings. Costs 0 units. 
    # @param query [String] Search term, min 3 characters
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<(Hash<String, String>, Integer, Hash)>] Hash<String, String> data, response status code and response headers
    def autocomplete_with_http_info(query, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddressApi.autocomplete ...'
      end
      # verify the required parameter 'query' is set
      if @api_client.config.client_side_validation && query.nil?
        fail ArgumentError, "Missing the required parameter 'query' when calling AddressApi.autocomplete"
      end
      if @api_client.config.client_side_validation && query.to_s.length < 3
        fail ArgumentError, 'invalid value for "query" when calling AddressApi.autocomplete, the character length must be greater than or equal to 3.'
      end

      allowable_values = ["au", "nz"]
      if @api_client.config.client_side_validation && opts[:'country'] && !allowable_values.include?(opts[:'country'])
        fail ArgumentError, "invalid value for \"country\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/autocomplete'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'query'] = query
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Hash<String, String>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AddressApi.autocomplete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddressApi#autocomplete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Address details
    # Fetch the full structured record for an address ID returned by /autocomplete. Costs 1 unit. 
    # @param id [String] Address ID from /autocomplete
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [AddressDetails]
    def autocomplete_details(id, opts = {})
      data, _status_code, _headers = autocomplete_details_with_http_info(id, opts)
      data
    end

    # Address details
    # Fetch the full structured record for an address ID returned by /autocomplete. Costs 1 unit. 
    # @param id [String] Address ID from /autocomplete
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<(AddressDetails, Integer, Hash)>] AddressDetails data, response status code and response headers
    def autocomplete_details_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddressApi.autocomplete_details ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling AddressApi.autocomplete_details"
      end
      allowable_values = ["au", "nz"]
      if @api_client.config.client_side_validation && opts[:'country'] && !allowable_values.include?(opts[:'country'])
        fail ArgumentError, "invalid value for \"country\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/autocomplete-details'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'id'] = id
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AddressDetails'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AddressApi.autocomplete_details",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddressApi#autocomplete_details\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Suburb autocomplete
    # Search for suburbs and localities across Australia and New Zealand. Returns a map of locality IDs to highlighted strings. Costs 0 units. 
    # @param query [String] Search term, min 2 characters
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Hash<String, String>]
    def autocomplete_suburb(query, opts = {})
      data, _status_code, _headers = autocomplete_suburb_with_http_info(query, opts)
      data
    end

    # Suburb autocomplete
    # Search for suburbs and localities across Australia and New Zealand. Returns a map of locality IDs to highlighted strings. Costs 0 units. 
    # @param query [String] Search term, min 2 characters
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<(Hash<String, String>, Integer, Hash)>] Hash<String, String> data, response status code and response headers
    def autocomplete_suburb_with_http_info(query, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddressApi.autocomplete_suburb ...'
      end
      # verify the required parameter 'query' is set
      if @api_client.config.client_side_validation && query.nil?
        fail ArgumentError, "Missing the required parameter 'query' when calling AddressApi.autocomplete_suburb"
      end
      if @api_client.config.client_side_validation && query.to_s.length < 2
        fail ArgumentError, 'invalid value for "query" when calling AddressApi.autocomplete_suburb, the character length must be greater than or equal to 2.'
      end

      allowable_values = ["au", "nz"]
      if @api_client.config.client_side_validation && opts[:'country'] && !allowable_values.include?(opts[:'country'])
        fail ArgumentError, "invalid value for \"country\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/autocomplete-suburb'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'query'] = query
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Hash<String, String>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AddressApi.autocomplete_suburb",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddressApi#autocomplete_suburb\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Suburb details
    # Get full details for a locality ID returned by /autocomplete-suburb. Costs 1 unit. For NZ results, state/stateFull are null; use region instead. NZ localities return postcode: null. 
    # @param id [String] Locality ID from /autocomplete-suburb
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [SuburbDetails]
    def autocomplete_suburb_details(id, opts = {})
      data, _status_code, _headers = autocomplete_suburb_details_with_http_info(id, opts)
      data
    end

    # Suburb details
    # Get full details for a locality ID returned by /autocomplete-suburb. Costs 1 unit. For NZ results, state/stateFull are null; use region instead. NZ localities return postcode: null. 
    # @param id [String] Locality ID from /autocomplete-suburb
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<(SuburbDetails, Integer, Hash)>] SuburbDetails data, response status code and response headers
    def autocomplete_suburb_details_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddressApi.autocomplete_suburb_details ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling AddressApi.autocomplete_suburb_details"
      end
      allowable_values = ["au", "nz"]
      if @api_client.config.client_side_validation && opts[:'country'] && !allowable_values.include?(opts[:'country'])
        fail ArgumentError, "invalid value for \"country\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/autocomplete-suburb-details'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'id'] = id
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SuburbDetails'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AddressApi.autocomplete_suburb_details",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddressApi#autocomplete_suburb_details\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Postcode lookup
    # Look up all suburbs and localities that belong to a postcode. Returns up to 50 results ordered alphabetically. Costs 1 unit. 
    # @param postcode [String] 4-digit postcode
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<PostcodeResult>]
    def postcode_lookup(postcode, opts = {})
      data, _status_code, _headers = postcode_lookup_with_http_info(postcode, opts)
      data
    end

    # Postcode lookup
    # Look up all suburbs and localities that belong to a postcode. Returns up to 50 results ordered alphabetically. Costs 1 unit. 
    # @param postcode [String] 4-digit postcode
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<(Array<PostcodeResult>, Integer, Hash)>] Array<PostcodeResult> data, response status code and response headers
    def postcode_lookup_with_http_info(postcode, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddressApi.postcode_lookup ...'
      end
      # verify the required parameter 'postcode' is set
      if @api_client.config.client_side_validation && postcode.nil?
        fail ArgumentError, "Missing the required parameter 'postcode' when calling AddressApi.postcode_lookup"
      end
      pattern = Regexp.new(/^\d{4}$/)
      if @api_client.config.client_side_validation && postcode !~ pattern
        fail ArgumentError, "invalid value for 'postcode' when calling AddressApi.postcode_lookup, must conform to the pattern #{pattern}."
      end

      allowable_values = ["au", "nz"]
      if @api_client.config.client_side_validation && opts[:'country'] && !allowable_values.include?(opts[:'country'])
        fail ArgumentError, "invalid value for \"country\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/postcode'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'postcode'] = postcode
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<PostcodeResult>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AddressApi.postcode_lookup",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddressApi#postcode_lookup\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Reverse geocode
    # Find the nearest address(es) to a coordinate pair. Results are ordered by distance. Costs 1 unit. 
    # @param lat [Float] Latitude (AU: −44 to −9, NZ: −47 to −34)
    # @param lng [Float] Longitude (AU: 112–155, NZ: 166–178)
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :radius Search radius in metres (1–5000, default 100) (default to 100)
    # @option opts [Integer] :limit Max results (1–10, default 1) (default to 1)
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<ReverseResult>]
    def reverse_geocode(lat, lng, opts = {})
      data, _status_code, _headers = reverse_geocode_with_http_info(lat, lng, opts)
      data
    end

    # Reverse geocode
    # Find the nearest address(es) to a coordinate pair. Results are ordered by distance. Costs 1 unit. 
    # @param lat [Float] Latitude (AU: −44 to −9, NZ: −47 to −34)
    # @param lng [Float] Longitude (AU: 112–155, NZ: 166–178)
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :radius Search radius in metres (1–5000, default 100) (default to 100)
    # @option opts [Integer] :limit Max results (1–10, default 1) (default to 1)
    # @option opts [String] :country Country dataset: au (default) or nz (default to 'au')
    # @return [Array<(Array<ReverseResult>, Integer, Hash)>] Array<ReverseResult> data, response status code and response headers
    def reverse_geocode_with_http_info(lat, lng, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AddressApi.reverse_geocode ...'
      end
      # verify the required parameter 'lat' is set
      if @api_client.config.client_side_validation && lat.nil?
        fail ArgumentError, "Missing the required parameter 'lat' when calling AddressApi.reverse_geocode"
      end
      # verify the required parameter 'lng' is set
      if @api_client.config.client_side_validation && lng.nil?
        fail ArgumentError, "Missing the required parameter 'lng' when calling AddressApi.reverse_geocode"
      end
      if @api_client.config.client_side_validation && !opts[:'radius'].nil? && opts[:'radius'] > 5000
        fail ArgumentError, 'invalid value for "opts[:"radius"]" when calling AddressApi.reverse_geocode, must be smaller than or equal to 5000.'
      end

      if @api_client.config.client_side_validation && !opts[:'radius'].nil? && opts[:'radius'] < 1
        fail ArgumentError, 'invalid value for "opts[:"radius"]" when calling AddressApi.reverse_geocode, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] > 10
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling AddressApi.reverse_geocode, must be smaller than or equal to 10.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] < 1
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling AddressApi.reverse_geocode, must be greater than or equal to 1.'
      end

      allowable_values = ["au", "nz"]
      if @api_client.config.client_side_validation && opts[:'country'] && !allowable_values.include?(opts[:'country'])
        fail ArgumentError, "invalid value for \"country\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/reverse'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'lat'] = lat
      query_params[:'lng'] = lng
      query_params[:'radius'] = opts[:'radius'] if !opts[:'radius'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<ReverseResult>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AddressApi.reverse_geocode",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AddressApi#reverse_geocode\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
