=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module Checkify
  class BusinessApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # ABN lookup
    # Validate an Australian Business Number and retrieve registered business details from the ABR. Costs 1 unit. 
    # @param abn [String] 11-digit ABN — spaces accepted
    # @param [Hash] opts the optional parameters
    # @return [AbnResponse]
    def abn_lookup(abn, opts = {})
      data, _status_code, _headers = abn_lookup_with_http_info(abn, opts)
      data
    end

    # ABN lookup
    # Validate an Australian Business Number and retrieve registered business details from the ABR. Costs 1 unit. 
    # @param abn [String] 11-digit ABN — spaces accepted
    # @param [Hash] opts the optional parameters
    # @return [Array<(AbnResponse, Integer, Hash)>] AbnResponse data, response status code and response headers
    def abn_lookup_with_http_info(abn, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BusinessApi.abn_lookup ...'
      end
      # verify the required parameter 'abn' is set
      if @api_client.config.client_side_validation && abn.nil?
        fail ArgumentError, "Missing the required parameter 'abn' when calling BusinessApi.abn_lookup"
      end
      # resource path
      local_var_path = '/abn'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'abn'] = abn

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AbnResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"BusinessApi.abn_lookup",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BusinessApi#abn_lookup\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # ACN lookup
    # Validate an Australian Company Number and retrieve registered company details from ASIC, including entity name, type, registration dates, addresses, former names, and recent documents. Costs 1 unit. 
    # @param acn [String] 9-digit ACN — spaces accepted
    # @param [Hash] opts the optional parameters
    # @return [AcnResponse]
    def acn_lookup(acn, opts = {})
      data, _status_code, _headers = acn_lookup_with_http_info(acn, opts)
      data
    end

    # ACN lookup
    # Validate an Australian Company Number and retrieve registered company details from ASIC, including entity name, type, registration dates, addresses, former names, and recent documents. Costs 1 unit. 
    # @param acn [String] 9-digit ACN — spaces accepted
    # @param [Hash] opts the optional parameters
    # @return [Array<(AcnResponse, Integer, Hash)>] AcnResponse data, response status code and response headers
    def acn_lookup_with_http_info(acn, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BusinessApi.acn_lookup ...'
      end
      # verify the required parameter 'acn' is set
      if @api_client.config.client_side_validation && acn.nil?
        fail ArgumentError, "Missing the required parameter 'acn' when calling BusinessApi.acn_lookup"
      end
      # resource path
      local_var_path = '/acn'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'acn'] = acn

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AcnResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"BusinessApi.acn_lookup",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BusinessApi#acn_lookup\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Business activity search
    # Search over 9,000 Australian business activities and industry classifications (ANZSIC codes) with fuzzy matching, misspelling correction, and relevance scoring. Costs 0 units. 
    # @param search [String] Search query, min 3 characters
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Max results (1–100, default 25) (default to 25)
    # @return [BusinessActivityResponse]
    def business_activity(search, opts = {})
      data, _status_code, _headers = business_activity_with_http_info(search, opts)
      data
    end

    # Business activity search
    # Search over 9,000 Australian business activities and industry classifications (ANZSIC codes) with fuzzy matching, misspelling correction, and relevance scoring. Costs 0 units. 
    # @param search [String] Search query, min 3 characters
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Max results (1–100, default 25) (default to 25)
    # @return [Array<(BusinessActivityResponse, Integer, Hash)>] BusinessActivityResponse data, response status code and response headers
    def business_activity_with_http_info(search, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BusinessApi.business_activity ...'
      end
      # verify the required parameter 'search' is set
      if @api_client.config.client_side_validation && search.nil?
        fail ArgumentError, "Missing the required parameter 'search' when calling BusinessApi.business_activity"
      end
      if @api_client.config.client_side_validation && search.to_s.length < 3
        fail ArgumentError, 'invalid value for "search" when calling BusinessApi.business_activity, the character length must be greater than or equal to 3.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] > 100
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling BusinessApi.business_activity, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] < 1
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling BusinessApi.business_activity, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/business-activity'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'search'] = search
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'BusinessActivityResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"BusinessApi.business_activity",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BusinessApi#business_activity\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Business name availability
    # Check whether a proposed business (trading) name is available for registration with ASIC. Costs 1 unit. 
    # @param name [String] Proposed business name (max 200 characters)
    # @param [Hash] opts the optional parameters
    # @return [NameAvailability]
    def business_name_check(name, opts = {})
      data, _status_code, _headers = business_name_check_with_http_info(name, opts)
      data
    end

    # Business name availability
    # Check whether a proposed business (trading) name is available for registration with ASIC. Costs 1 unit. 
    # @param name [String] Proposed business name (max 200 characters)
    # @param [Hash] opts the optional parameters
    # @return [Array<(NameAvailability, Integer, Hash)>] NameAvailability data, response status code and response headers
    def business_name_check_with_http_info(name, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BusinessApi.business_name_check ...'
      end
      # verify the required parameter 'name' is set
      if @api_client.config.client_side_validation && name.nil?
        fail ArgumentError, "Missing the required parameter 'name' when calling BusinessApi.business_name_check"
      end
      if @api_client.config.client_side_validation && name.to_s.length > 200
        fail ArgumentError, 'invalid value for "name" when calling BusinessApi.business_name_check, the character length must be smaller than or equal to 200.'
      end

      # resource path
      local_var_path = '/business-name'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'name'] = name

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'NameAvailability'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"BusinessApi.business_name_check",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BusinessApi#business_name_check\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Company name availability
    # Check whether a proposed company name is available for registration with ASIC. Costs 1 unit. 
    # @param name [String] Proposed company name (max 200 characters)
    # @param [Hash] opts the optional parameters
    # @return [NameAvailability]
    def company_name_check(name, opts = {})
      data, _status_code, _headers = company_name_check_with_http_info(name, opts)
      data
    end

    # Company name availability
    # Check whether a proposed company name is available for registration with ASIC. Costs 1 unit. 
    # @param name [String] Proposed company name (max 200 characters)
    # @param [Hash] opts the optional parameters
    # @return [Array<(NameAvailability, Integer, Hash)>] NameAvailability data, response status code and response headers
    def company_name_check_with_http_info(name, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BusinessApi.company_name_check ...'
      end
      # verify the required parameter 'name' is set
      if @api_client.config.client_side_validation && name.nil?
        fail ArgumentError, "Missing the required parameter 'name' when calling BusinessApi.company_name_check"
      end
      if @api_client.config.client_side_validation && name.to_s.length > 200
        fail ArgumentError, 'invalid value for "name" when calling BusinessApi.company_name_check, the character length must be smaller than or equal to 200.'
      end

      # resource path
      local_var_path = '/company-name'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'name'] = name

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'NameAvailability'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"BusinessApi.company_name_check",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BusinessApi#company_name_check\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
