=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module Checkify
  class CommunicationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Email validation
    # Validate an email address — checks RFC format, DNS/MX records, SMTP deliverability, disposable/free/role detection, and quality score. Costs 1 unit. 
    # @param email [String] Email address to validate (max 254 characters)
    # @param [Hash] opts the optional parameters
    # @return [EmailResponse]
    def email_validation(email, opts = {})
      data, _status_code, _headers = email_validation_with_http_info(email, opts)
      data
    end

    # Email validation
    # Validate an email address — checks RFC format, DNS/MX records, SMTP deliverability, disposable/free/role detection, and quality score. Costs 1 unit. 
    # @param email [String] Email address to validate (max 254 characters)
    # @param [Hash] opts the optional parameters
    # @return [Array<(EmailResponse, Integer, Hash)>] EmailResponse data, response status code and response headers
    def email_validation_with_http_info(email, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CommunicationApi.email_validation ...'
      end
      # verify the required parameter 'email' is set
      if @api_client.config.client_side_validation && email.nil?
        fail ArgumentError, "Missing the required parameter 'email' when calling CommunicationApi.email_validation"
      end
      if @api_client.config.client_side_validation && email.to_s.length > 254
        fail ArgumentError, 'invalid value for "email" when calling CommunicationApi.email_validation, the character length must be smaller than or equal to 254.'
      end

      # resource path
      local_var_path = '/email'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'email'] = email

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'EmailResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"CommunicationApi.email_validation",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CommunicationApi#email_validation\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Phone validation
    # Validate and normalise a phone number. Detects country, returns E.164 / national / international formats, line type, carrier, and location. Defaults to AU parsing. Costs 1 unit. 
    # @param phone [String] Phone number to validate — include country code or use the country hint
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country ISO 3166-1 alpha-2 country code hint for local numbers (default AU) (default to 'AU')
    # @return [PhoneResponse]
    def phone_validation(phone, opts = {})
      data, _status_code, _headers = phone_validation_with_http_info(phone, opts)
      data
    end

    # Phone validation
    # Validate and normalise a phone number. Detects country, returns E.164 / national / international formats, line type, carrier, and location. Defaults to AU parsing. Costs 1 unit. 
    # @param phone [String] Phone number to validate — include country code or use the country hint
    # @param [Hash] opts the optional parameters
    # @option opts [String] :country ISO 3166-1 alpha-2 country code hint for local numbers (default AU) (default to 'AU')
    # @return [Array<(PhoneResponse, Integer, Hash)>] PhoneResponse data, response status code and response headers
    def phone_validation_with_http_info(phone, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CommunicationApi.phone_validation ...'
      end
      # verify the required parameter 'phone' is set
      if @api_client.config.client_side_validation && phone.nil?
        fail ArgumentError, "Missing the required parameter 'phone' when calling CommunicationApi.phone_validation"
      end
      # resource path
      local_var_path = '/phone'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'phone'] = phone
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PhoneResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"CommunicationApi.phone_validation",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CommunicationApi#phone_validation\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
