=begin
#Checkify API

#Australian and New Zealand address validation, business lookups, identity checks, and communication validation through a single REST interface.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module Checkify
  class IdentityApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Director ID validation
    # Validate the format and checksum of an Australian Director Identification Number using the official ABRS Damm algorithm. Structural check only — no live ABRS registry lookup. Costs 1 unit. 
    # @param director_id [String] 15-digit Director ID starting with 036 — spaces accepted
    # @param [Hash] opts the optional parameters
    # @return [DirectorIdResponse]
    def director_id_validation(director_id, opts = {})
      data, _status_code, _headers = director_id_validation_with_http_info(director_id, opts)
      data
    end

    # Director ID validation
    # Validate the format and checksum of an Australian Director Identification Number using the official ABRS Damm algorithm. Structural check only — no live ABRS registry lookup. Costs 1 unit. 
    # @param director_id [String] 15-digit Director ID starting with 036 — spaces accepted
    # @param [Hash] opts the optional parameters
    # @return [Array<(DirectorIdResponse, Integer, Hash)>] DirectorIdResponse data, response status code and response headers
    def director_id_validation_with_http_info(director_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: IdentityApi.director_id_validation ...'
      end
      # verify the required parameter 'director_id' is set
      if @api_client.config.client_side_validation && director_id.nil?
        fail ArgumentError, "Missing the required parameter 'director_id' when calling IdentityApi.director_id_validation"
      end
      # resource path
      local_var_path = '/director-id'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'director_id'] = director_id

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'DirectorIdResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"IdentityApi.director_id_validation",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: IdentityApi#director_id_validation\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Sanctions screening
    # Screen an individual or entity name against 11 sanctions and debarment lists including DFAT, UN, OFAC SDN, EU, UK OFSI, Canada, New Zealand, France, Hong Kong, World Bank, and IDB. Costs 3 units. 
    # @param name [String] Full name to screen (3–200 characters)
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :birth_year Year of birth (1900–2008) — boosts confidence if matched
    # @option opts [String] :country ISO 3166-1 alpha-2 country code — boosts confidence if matched
    # @option opts [String] :city City of birth (max 200 characters) — fuzzy-compared for confidence boost
    # @return [SanctionsResponse]
    def sanctions_screening(name, opts = {})
      data, _status_code, _headers = sanctions_screening_with_http_info(name, opts)
      data
    end

    # Sanctions screening
    # Screen an individual or entity name against 11 sanctions and debarment lists including DFAT, UN, OFAC SDN, EU, UK OFSI, Canada, New Zealand, France, Hong Kong, World Bank, and IDB. Costs 3 units. 
    # @param name [String] Full name to screen (3–200 characters)
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :birth_year Year of birth (1900–2008) — boosts confidence if matched
    # @option opts [String] :country ISO 3166-1 alpha-2 country code — boosts confidence if matched
    # @option opts [String] :city City of birth (max 200 characters) — fuzzy-compared for confidence boost
    # @return [Array<(SanctionsResponse, Integer, Hash)>] SanctionsResponse data, response status code and response headers
    def sanctions_screening_with_http_info(name, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: IdentityApi.sanctions_screening ...'
      end
      # verify the required parameter 'name' is set
      if @api_client.config.client_side_validation && name.nil?
        fail ArgumentError, "Missing the required parameter 'name' when calling IdentityApi.sanctions_screening"
      end
      if @api_client.config.client_side_validation && name.to_s.length > 200
        fail ArgumentError, 'invalid value for "name" when calling IdentityApi.sanctions_screening, the character length must be smaller than or equal to 200.'
      end

      if @api_client.config.client_side_validation && name.to_s.length < 3
        fail ArgumentError, 'invalid value for "name" when calling IdentityApi.sanctions_screening, the character length must be greater than or equal to 3.'
      end

      if @api_client.config.client_side_validation && !opts[:'birth_year'].nil? && opts[:'birth_year'] > 2008
        fail ArgumentError, 'invalid value for "opts[:"birth_year"]" when calling IdentityApi.sanctions_screening, must be smaller than or equal to 2008.'
      end

      if @api_client.config.client_side_validation && !opts[:'birth_year'].nil? && opts[:'birth_year'] < 1900
        fail ArgumentError, 'invalid value for "opts[:"birth_year"]" when calling IdentityApi.sanctions_screening, must be greater than or equal to 1900.'
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if @api_client.config.client_side_validation && !opts[:'country'].nil? && opts[:'country'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"country\"]' when calling IdentityApi.sanctions_screening, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'city'].nil? && opts[:'city'].to_s.length > 200
        fail ArgumentError, 'invalid value for "opts[:"city"]" when calling IdentityApi.sanctions_screening, the character length must be smaller than or equal to 200.'
      end

      # resource path
      local_var_path = '/sanctions-screening'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'name'] = name
      query_params[:'birth_year'] = opts[:'birth_year'] if !opts[:'birth_year'].nil?
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?
      query_params[:'city'] = opts[:'city'] if !opts[:'city'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SanctionsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"IdentityApi.sanctions_screening",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: IdentityApi#sanctions_screening\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # TFN validation
    # Validate the format and checksum of an Australian Tax File Number. Structural check only — no live ATO registry lookup. Costs 1 unit. 
    # @param tfn [String] 8 or 9-digit TFN — spaces and hyphens accepted
    # @param [Hash] opts the optional parameters
    # @return [TfnResponse]
    def tfn_validation(tfn, opts = {})
      data, _status_code, _headers = tfn_validation_with_http_info(tfn, opts)
      data
    end

    # TFN validation
    # Validate the format and checksum of an Australian Tax File Number. Structural check only — no live ATO registry lookup. Costs 1 unit. 
    # @param tfn [String] 8 or 9-digit TFN — spaces and hyphens accepted
    # @param [Hash] opts the optional parameters
    # @return [Array<(TfnResponse, Integer, Hash)>] TfnResponse data, response status code and response headers
    def tfn_validation_with_http_info(tfn, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: IdentityApi.tfn_validation ...'
      end
      # verify the required parameter 'tfn' is set
      if @api_client.config.client_side_validation && tfn.nil?
        fail ArgumentError, "Missing the required parameter 'tfn' when calling IdentityApi.tfn_validation"
      end
      # resource path
      local_var_path = '/tfn'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'tfn'] = tfn

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TfnResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"IdentityApi.tfn_validation",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: IdentityApi#tfn_validation\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
